version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
    networks:
      - reseau1

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: motdepasse
    ports:
      - "8080:80"
    networks:
      - reseau1

networks:
  reseau1:
    driver: bridge